### ISSUE TITLE
Ghost issue in first person with Custom Enhanced Camera

### ISSUE THREAD

**Issue by arafuse** [mcstfuerson/TES-Reloaded#29]
I experienced the bug reported by others on the Nexus here: 
https://www.nexusmods.com/oblivion/mods/51032?tab=bugs&BH=0

Easy steps to reproduce:
1. Install ORE3, enable underwater shader (or godrays or other effect that uses the depth buffer.)
2. Install https://www.nexusmods.com/oblivion/mods/50125 (keep first person shadows option disabled in ini or it will crash.)
3. Ingame, go underwater and flip between first and third person. You'll see the depth buffer afterimage.

The fix for me was to comment part of line 383 in `RenderHook.cpp` to always resolve the depth buffer if the `Object == WorldSceneGraph`:

```cpp
void (__cdecl * RenderObject)(NiCamera*, NiNode*, NiCullingProcess*, NiVisibleArray*) = (void (__cdecl *)(NiCamera*, NiNode*, NiCullingProcess*, NiVisibleArray*))0x0070C0B0;
void __cdecl TrackRenderObject(NiCamera* Camera, NiNode* Object, NiCullingProcess* CullingProcess, NiVisibleArray* VisibleArray) {
	
	bool CameraMode = TheSettingManager->SettingsMain.CameraMode.Enabled;

	RenderObject(Camera, Object, CullingProcess, VisibleArray);
	// Fix for Enhanced Camera
	if (Object == WorldSceneGraph) { // && (CameraMode || Player->IsThirdPersonView(CameraMode, TheRenderManager->FirstPersonView))) {
		TheRenderManager->ResolveDepthBuffer();
	}
	else if (Object == Player->firstPersonNiNode) {
		TheRenderManager->ResolveDepthBuffer();
		TheRenderManager->Clear(NULL, NiRenderer::kClear_ZBUFFER);
		RenderObject(Camera, Object, CullingProcess, VisibleArray);
	}
}
```

**Comment by mcstfuerson** [comment]
Thanks for submitting. I will add this to next release if everything tests OK, seems promising.
